-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: v1.0.0
    hooks:
    -   id: remove-crlf
    -   id: remove-tabs
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 3fa02652357ff0dbb42b5bc78c673b7bc105fcf3
    hooks:
    -   id: trailing-whitespace
        args:
        - --no-markdown-linebreak-ext
    -   id: check-yaml
-   repo: git://github.com/pre-commit/mirrors-pylint
    sha: 4de6c8dfadef1a271a814561ce05b8bc1c446d22
    hooks:
    -   id: pylint
        args:
        - --rcfile=.pylintrc
        - --reports=no
