-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: remove-crlf
    -   id: remove-tabs
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: trailing-whitespace
        args:
        - --no-markdown-linebreak-ext
    -   id: check-yaml
-   repo: git://github.com/pre-commit/mirrors-pylint
    sha: v1.7.2
    hooks:
    -   id: pylint
        args:
        - --rcfile=.pylintrc
        - --reports=no
-   repo: local
    hooks:
    -   id: py.test
        name: py.test
        language: system
        entry: sh -c py.test
        files: ''
